# dataset
class_num: 80  # number of classes
data_path: ./val2017  # dataset root dir
gt: ./instances_val2017.json  # val annotation file

# model
model: yolov5s.pt  # yolov5[n/s/m/l/x]
tag: 6.1  # yolov5 tags [2.0/3.1/4.0/5.0/6.0/6.1]

# parameters
batch_size: 1
image_size: [640, 640]
conf_thres: 0.4  # object confidence threshold
iou_thres: 0.5  # IOU threshold for NMS
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# quantify
type: fp16  # data type [fp16/int8]
calib_bs: 16  # batch size of calibration data (int8 use only), recommend: 16

# om_infer
soc: Ascend310P3  # soc version [Ascend310/Ascend310P?]
cann_path: /usr/local/Ascend/ascend-toolkit
output_dir: output  # result output dir
test_acc: nms_op  # nms compute mode [nms_op/nms_script]
test_perf: False  # whether to test performance [True/False]